RE-1590 Install pkg-config with libvirt-dev
Without pkg-config the libvirt-python compilation fails with:

Exception: pkg-config binary is required to compile libvirt-python